### ISSUE TITLE
WineD3D + SweetFX 

### ISSUE THREAD

**Issue by CHNSK** [elishacloud/LoadWineD3D-ASI#1]
Hi elishacloud, let me be the first troublemaker here;

I'm having a weird problem when use WineD3D's and SweetFX' d3d9.dlls together: I get black-screen; but the game is launching and running, I can even manipulate it and hear the sound when I move the cursor and load the game and all I can see is the blackscreen. The game is Silent Hill 2 by the way. My folder structure is: 

Scripts folder: 

- LoadWine3D3.asi
- LoadWine3D3.log
- d3d9.dll
- libwine.dll
- wined3d

And of course Widescreen Fix Package files and other asi files.

Main folder:

- SweetFX 1.4 files, including its d3d9.dll

Could you give me any advice on this?

**Comment by elishacloud** [comment]
This could be an issue with the way WineD3D and SweetFX work together.  I doubt this is an issue with this ASI.  What are you using SweetFX for?  Have you tried using [injectSMAA](http://mrhaandi.blogspot.com/p/injectsmaa.html) instead?

**Comment by CHNSK** [comment]
I don't use SweetFX for AA-which I can't force it anyway- I  use it to rid off the bleached look of PC version and make it game more like PS2 version.

**Comment by CHNSK** [comment]
Strange thing: I'm not sure how but it's working now, I've just downloaded and tried again, I don't remember but WineD3D 2.20 must be a new version and that's why it worked.
